### ISSUE TITLE
Handle narrow screens better with app bar

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#208]
When on a small screen, the app bar can wrap.  In Android, the buttons to the right can go to a menu.  We should handle this better. Breakpoints?

![image](https://user-images.githubusercontent.com/517814/234632014-e0c4e5e8-7524-4016-a339-7dc897d77379.png)

**Comment by chrisvire** [comment]
Android has an ActionBar that hides icons when there is not enough room.

**Comment by Caleb-Parks** [comment]
Solution:
-Always show only three icons, evenly spaced.
-If there are more then three to show, make the third a menu.
-Menu should show icons with names.

**Comment by chrisvire** [comment]
I turned off the search, book collection (make only one collection), and audio icons.  There is still a problem with the left side.



![Image](https://github.com/sillsdev/appbuilder-pwa/assets/517814/53a9915a-913d-4732-84f6-e33921d5da9e)

**Comment by chrisvire** [comment]
This is what I think needs to be done:

- we need to use Flex Box or Grid to layout the items in the row so that we don't get the current overflow of the book and chapter controls
- If there are more than X number of controls (where X might be 2 or 3), then show the 1 or 2 icons to the left and hide the read and have a "disclosure" icon to get the rest (probably using the "Arrow Left" icon from https://fonts.google.com/icons).
- When the Arrow Left button is tapped, then hide the left buttons area and show all the right buttons.
- Once one of the Right buttons is tapped, then revert back to original arrangement.

**Comment by Caleb-Parks** [comment]
Updated Design Goal (mobile):
- Display the audio button if there is audio
- Display the text appearance button
- Hide all the rest under a more button
- When we click the more button, we could display an icon menu that pops up over the more button and shows all the buttons.

**Comment by chrisvire** [comment]
Current implementation (sample at https://pwa-pr-208.surge.sh):

Hidden:

![image](https://github.com/sillsdev/appbuilder-pwa/assets/517814/3b7c8360-506f-4135-8f90-69a8aac4ea7f)

Expanded:

![image](https://github.com/sillsdev/appbuilder-pwa/assets/517814/cd607912-4ca8-405f-90ee-68d6216127d7)

**Comment by chrisvire** [comment]
@Caleb-Parks working on the rest of the implementation with #276

**Comment by chrisvire** [comment]
I sent an email to @rpmargetts to get his feedback on what you have done so fair. Waiting on that.
