### ISSUE TITLE
Hover colours on chapter and verse numbers in selector

### ISSUE THREAD

**Issue by rpmargetts** [sillsdev/appbuilder-pwa#228]
When you touch over the chapter and verse numbers in the Android app, notice how the colour changes to something slightly darker when your finger is touching each button. It would be nice to reproduce this in the PWA.

**Comment by chrisvire** [comment]
@rpmargetts I believe the background color comes from ui.button.book-grid { background-color }.  How are you determining the color for the touch? Are you just adjusting the HLS of the background-color ?
