### ISSUE TITLE
Replace 'Loading...' by a spinning circle

### ISSUE THREAD

**Issue by rpmargetts** [sillsdev/appbuilder-pwa#231]
When a page is loading, it would be better to see a spinning circle rather than the word 'Loading...'

**Comment by chrisvire** [comment]
@rpmargetts, Is there a specific spinning circle that you would like? I can imagine that you have an opinion.

There is an example here:
https://www.w3docs.com/snippets/css/how-to-create-loading-spinner-with-css.html

Scriptoria doesn't use a circle, but uses this:

<img width="153" alt="image" src="https://github.com/sillsdev/appbuilder-pwa/assets/517814/043b9e93-c7db-4fa0-80e8-e5300d1f1664">

Implemented by:
https://github.com/sillsdev/appbuilder-portal/blob/develop/source/SIL.AppBuilder.Portal.Frontend/src/ui/components/loading-wrapper/index.tsx

**Comment by chrisvire** [comment]
@rpmargetts If you have time today, could you comment if you have a preference for the spinning circle animation? Otherwise, we will likely do the one in the w3docs example.

**Comment by rpmargetts** [comment]
@chrisvire The example in w3docs above would be fine.

But notice that this icon has a blue highlight to it. You could either modify the blue to be in line with the colour scheme, or more easily replace the blue by a darker grey - which could be used by any colour scheme.

**Comment by chrisvire** [comment]
@rpmargetts, the CSS component library that we are using has a loading component.

https://daisyui.com/components/loading/

I believe we are using the spinner style. If you want a different one, please let me know
