### ISSUE TITLE
Display Note icon in chapter

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#245]
Like bookmarks, there should be an icon in the text that indicates that there is a note for the verse.  This will be very similar to the implementation for bookmarks.  The code will be in src/lib/components/ScriptureViewSophria.svelte

**Comment by ChristopherRankin** [comment]
Enabled notes to be stored in local storage.

**Comment by ChristopherRankin** [comment]
Updated NoteIcon.svelte to be consistent with the android app.
