### ISSUE TITLE
Dynamically Update Book/Chapter Selector

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#259]
Books/Chapter selector contents do not reactively update when selecting a new book collection

When Dioula is selected

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/8645680d-cbbe-4c7c-b995-0529cd456185)

the following books are available

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/0b1bb8fa-5128-4569-ad53-6c5995172e11)

When french is selected 

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/3d8a8799-c6b5-4a92-a8e9-07d8d33819ff)

The available books remain the same 

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/5d81d8ab-9d72-4462-b0da-85fd5a1a72b6)

yet should be 

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/5395cc74-2c98-4305-ac23-5008dbcb2b20)

See [svelte reactivity](https://svelte.dev/tutorial/reactive-declarations) to implement this

**Comment by chrisvire** [comment]
Fixed by #274
