### ISSUE TITLE
Bug: on narrow screen, chapter selector goes off the edge of the screen

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#264]
![Image](https://github.com/sillsdev/appbuilder-pwa/assets/517814/8a18d5b5-8a08-4dad-bcdd-8323f2a7c40b)

Use a breakpoint so that this doesn't happen. Change the dropdown edge?

**Comment by Caleb-Parks** [comment]
#270 contains this issue.
