### ISSUE TITLE
Bug: mute audio button (in navbar) does not pause/stop playback.

### ISSUE THREAD

**Issue by Caleb-Parks** [sillsdev/appbuilder-pwa#268]
After clicking the audio button in the navbar and pressing play on the audio controls, playback does not pause or stop when the navbar audio button is pressed again (even though the playback controls disappear).

This leaves the user with no way to stop audio playback: if they press the navbar audio button again to bring back the playback controls and try to press the play/pause button, a new audio playback starts (in addition to the first one, resulting in confusing layered audio) rather than pausing the existing audio playback.

**Comment by chrisvire** [comment]
Added to #249
