### ISSUE TITLE
Bug: selector menus positioned realitive to buttons, not screen

### ISSUE THREAD

**Issue by Caleb-Parks** [sillsdev/appbuilder-pwa#270]
The text appearance, book, and chapter selector popup menus go off the screen on mobile because their positioning is coded relative to the button that brings them up, rather than the entire screen.

**Comment by Caleb-Parks** [comment]
Text appearance and collection selectors resolved in #208. Chapter and book selectors still need to be fixed.

**Comment by davidmoore1** [comment]
I think this one is resolved

**Comment by davidmoore1** [comment]
Discussed with Chris and he agreed that this appears to work for the smallest device mode
