### ISSUE TITLE
Menu Items Icons Theming

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#272]
Menu items icons need to be updated to match the theming of other icons in the drawer menu

![Image](https://user-images.githubusercontent.com/78440533/245213404-98cf68eb-ef61-4228-80f7-a8c2b4155a3c.png)

![Image](https://user-images.githubusercontent.com/78440533/245213479-be423a71-fb9a-4dcd-8396-34a74eccabbf.png)

**Comment by chrisvire** [comment]
Actually, this is really easy with Tailwind CSS `invert` class.
