### ISSUE TITLE
Bug: In hover, touch down in one cell and touch up in another doesn't select cell

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#284]
The new hover functionality styles the button the user is touching.  However, if you touch down in one cell and move your finger around (cell colors change) and then touch up in another cell, then that cell should be activated as the selection and it is not.

**Comment by jakedcolbert** [comment]
@chrisvire Waiting for confirmation if this is a feature desirable in the PWA or if we will revert to the behavior of the mobile application.

**Comment by chrisvire** [comment]
@jakedcolbert I haven't heard back from Richard yet.

**Comment by davidmoore1** [comment]
Since the fix for this one was closed, I suspect that the issue needs to be closed as well.  Either that or updated.

**Comment by chrisvire** [comment]
The issue is still there, but I don't know how important it is to fix. I believe I had received feedback about this from Richard. 

I tried it on Android again and it isn't consistent there.
