### ISSUE TITLE
Bug: Reset CollectionSelector button highlight

### ISSUE THREAD

**Issue by Caleb-Parks** [sillsdev/appbuilder-pwa#287]
When the popup is canceled/closed without applying changes (via the CANCEL button or tapping outside the modal), the CollectionSelector doesn't reset which option is highlighted. This results in a misleading UX when the user reopens the CollectionSelector: clicking OK will not necessarily apply the highlighted changes.

![Image](https://user-images.githubusercontent.com/78446583/247776177-9116f511-16d3-4efc-9886-6463771dea39.png)

**Comment by jakedcolbert** [comment]
Duplicate of #239
