### ISSUE TITLE
Layout Configuration: Open on launch

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#290]
Add support to open the CollectionSelector on launch using `config.mainFeatures["layout-config-first-launch"];`

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/0eb32b07-ea43-41dc-b41f-0d3c23e250f2)

**Comment by jakedcolbert** [comment]
@chrisvire Is there a distinction between on first launch and every launch?

**Comment by chrisvire** [comment]
@jakedcolbert You can test it out with the Android app.  I would have to as well since I don't know.

**Comment by jakedcolbert** [comment]
@chrisvire After testing on the android app, it only opens on the FIRST launch and does not open at relaunch.
