### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#295]

**Comment by chrisvire** [comment]
Here is a recording of a meeting with Mark Howe about how to use proskomma to do the search.

https://drive.google.com/file/d/1uOUKFkilMlQM9udxL-IQ4sFf2bwxSqX-/view?usp=sharing

**Comment by davidmoore1** [comment]
Search may be triggered from either the Search menu item on the slide drawer menu, or from the hourglass icon on the top right navigation bar.

The search selection screen is a full screen modal window.

A search text screen appears at the top of the screen.  It is formatted to use the font associated with the current book collection.  Search is only searching the current book collection.  When in dual pane or verse by verse mode (still to be implemented), search is only searching the current first book collection.

I am going to make separate issues for special character keyboard, matching whole word options and matching characters regardless of accents or tones.

A search button appears on the screen under the special characters.  In the apps, the return bar is changed to an hourglass icon in the keyboard display.  If this is possible, do that in PWA as well, but in either case, I think it would be consistent that return is also treated as a "Search" initiation 
command.


![Image](https://github.com/sillsdev/appbuilder-pwa/assets/6209188/ec4a7705-570d-4373-98a8-0948416bdcd3)

The search results screen is displayed as soon as the search is started.  This screen is also a full screen modal window with a scrollable window in which the matches are placed and a status line below that window.    The screen contains a back arrow which returns you to the search selection window.  

As matches are found, they are added to the screen.  The search results are placed in a scrollable window.  While the search is in progress, a text (Search_Searching)  "Searching..." is displayed at the bottom left of the screen, below the scroll window containing the results.  A count of the matches found so far (Search_Number_Found) "Found: %,d" is displayed on the far right bottom.

Each match entry displays the reference of the match in bold.  Underneath that is the text of the selected verse.  Each match within that verse (there may be more than one match in a single verse) is displayed in bold letters.  

If a match entry is tapped, the search window exits.  It navigates to the reference of the match in the main scripture window, briefly highlighting the verse.


![Image](https://github.com/sillsdev/appbuilder-pwa/assets/6209188/aed70375-32a5-4fbf-8252-9d43870d0cfc)

**Comment by davidmoore1** [comment]
If the search completes without finding a match, "No matches found" (Search_No_Matches_Found) is displayed along with a Search button that returns the app to the search text selection window, with the previously entered search text in the text field.
![SearchNoMatch](https://github.com/sillsdev/appbuilder-pwa/assets/6209188/8fc74774-a779-4bd8-a57b-7fee4add95da)
