### ISSUE TITLE
Annotation: Remove Text Notes

### ISSUE THREAD

**Issue by davidbbryant** [sillsdev/appbuilder-pwa#314]
When bookmarking, notating, or highlighting a verse with built-in translation notes, those notes will appear in the text that in that annotation's respective menu. This looks awkward, so it should probably be removed

**Comment by chrisvire** [comment]
@davidbbryant Could you provide some screenshots?

**Comment by chrisvire** [comment]
I will ask the Proskomma author (or @davidmoore1) if there is a way to do a query for specific verses that gets just the displayable text without markup.

**Comment by davidbbryant** [comment]
![Image](https://github.com/sillsdev/appbuilder-pwa/assets/123591459/09fb224f-e9f7-4d5f-ba1e-338c025a784e)



![Image](https://github.com/sillsdev/appbuilder-pwa/assets/123591459/c8b94fe4-83d7-4840-86a4-0739694a1aa2)
