### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#35]
Implement display footnotes (started in branch `footnote`)

**Comment by davidmoore1** [comment]
I believe that the footnote display is now basically complete.  There is probably still a need to display the text a little more as verse markers etc, but I believe that should be a separate issue.

**Comment by davidmoore1** [comment]
Basic feature has been implemented.  There are some other formatting issues that are covered in another issue but the general feature is complete
