### ISSUE TITLE
Feature: Viewing Footnotes

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#369]
USFM has tags for viewing footnotes.  ScriptureViewSofria is rendering these into the HTML with the contents of the footnote reference (fr) and text (ft) as inline `div` with `style="display:none;"`.

The footnotes will be in a span with data-graft="X-N" class="footnote".  Here is an example:

```
<span data-graft="X-1" class="footnote">
    <a>
        <sup>a</sup>
    </a>
    <div id="X-1" type="footnote" nc="+" style="display: none;">
        <span class="fr">1:1 </span>
        <span class="ft">Messiah (Hebrew) and Christ (Greek) both mean “Anointed One”</span>
    </div>
</span>
```

So we need to hyperlink the `<sup>` element and display the contents of the `<div id="X-1">` in a DaisyUI stack (they can nest).

Look at the rendered HTML from the Android App as to how it should look.

Use `<div id="container">` (where you see `<body>` in the footnote html) to inherit styling.

**Comment by jakedcolbert** [comment]
```html
<div id="X-6" type="xref" nc="+" style="display: none;"> 
  <span class="xo">1:23 </span>
  <span class="xt">Isaiah 7:14</span>
</div>
```
