### ISSUE TITLE
Feature: Footnotes with References

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#388]
There are 2 different footnote objects with inner HTML: 

```html
<div id="X-6" type="xref" nc="+" style="display: none;"> 
  <span class="xo">1:23 </span>
  <span class="xt">Isaiah 7:14</span>
</div>

<div id="X-2" type="xref" nc="+" style="display: none;">
  <span class="xo">27:10 </span>
  <span class="xt">Zechariah 11:12-13; Jeremiah 19:1-13; 32:6-9</span>
</div>
```

create a `scripture-reference.ts` file to have functions that process reference text into links that can navigate to the reference using the correct notation provided by SAB:

Navigation > Book Navigation > References : 
![Image](https://github.com/sillsdev/appbuilder-pwa/assets/78440533/3aecdfb2-5e32-4e72-ab3b-d1a794dd4fe3)

Books/\<Book Collection\>/Scripture References
![](https://cdn.discordapp.com/attachments/1024687582879154286/1136046712608260216/image.png)

**Comment by davidmoore1** [comment]
Fixed in PR https://github.com/sillsdev/appbuilder-pwa/pull/445
