### ISSUE TITLE
Bug: Footnotes look ugly on mobile

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#393]
resolve to fit screen width or track the scripture view's width. 

![Image](https://user-images.githubusercontent.com/78440533/258209937-6662d95c-495b-46b1-ab6b-7043e11e524d.png)

**Comment by davidmoore1** [comment]
The specific issue mentioned here appears to have been resolved.  Footnote now tracks to the screen width
