### ISSUE TITLE
Footnotes: Markdown links

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#401]
Footnotes can have Markdown links

https://community.scripture.software.sil.org/t/markup-links-in-footnotes-not-working-anymore-in-android-apps/1431

**Comment by chrisvire** [comment]
See this comment:
https://community.scripture.software.sil.org/t/markup-links-in-footnotes-not-working-anymore-in-android-apps/1431/11

**Comment by davidmoore1** [comment]
Fixed in commit #432
