### ISSUE TITLE
Category: Navigation

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#41]
- List Dropdown
- Grid Dropdown
- Book/Chapter/Verse
- Swipe between books
- First Book and Chapter
- Features > Navigation Settings
- Settings Screen
- Content Screens and Subscreens 
  - Optionally show on start up
  - Can switch between book collections
  - Can switch display mode (single/two screen/verse by verse
  - Contents Title Display options
- Tap on displayed link
- Automatic advance between chapters when playing audio
- Automatic advance between books when playing audio
- Tap on verse number, advancing audio and highlighting verse

**Comment by davidmoore1** [comment]
I believe all of these items are now completed.  If there are individual items that are found to need work, individual issues should be opened.

**Comment by davidmoore1** [comment]
As a general issue, these have been addressed.  Contents menus still have not been implemented, but will be covered under a separate future issue.
