### ISSUE TITLE
Book Name used for Cross References

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#419]
From:
https://community.scripture.software.sil.org/t/book-name-used-for-cross-references/4099

In the .appDef, you can have:

``` 
<book id="JOL"> 
    <name>Yuwiil (Joël)</name>
    <abbrev>Yuw</abbrev>
    <additional-names>
        <name>Yuwiil</name>
    </additional-names>
```

**Comment by davidmoore1** [comment]
Code needs to be added to convert config to pass the additional name through to the pwa app.
