### ISSUE TITLE
Share App options

### ISSUE THREAD

**Issue by jakedcolbert** [sillsdev/appbuilder-pwa#55]
> * Should the Share App button be turned invisible if none of the sharing options are selected in scripture app builder?

If there are no share options enabled, then the share menu is not visible.

> * How will the button handle App Store redirection and Google Play redirection if both are toggled?

If there are multiple, show a popup to select which one.  You can see how Android does this.  Actually, Android doesn't show a link for Apple Store.  For PWA, I would like you to show options for all. Look for images on the web (try to use svg and see icons in `src/lib/icons`).

Apple App Store Guidelines: https://developer.apple.com/app-store/marketing/guidelines/
Google Play Guidelines https://play.google.com/intl/en_us/badges/

These are formatted URLs.

Google Play:  https://play.google.com/store/apps/details?id=*package* (found in package root element)
Apple Store: https://apps.apple.com/us/app/id*share-apple-id* (found in features)

>   
>   * Is that handled in the sidebar component code?

What I would suggest is that there is a service for copying data to the clipboard.  The sidebar can assign the url to a store with "displayname" and "text" properties.  A service would be listening for updates to the store and would put the data into the clipboard and create a toast (from DaisyUI) notifying the user that "displayname set in clipboard"

_Originally posted by @chrisvire in https://github.com/sillsdev/appbuilder-pwa/issues/54#issuecomment-1271035251_

**Comment by chrisvire** [comment]
@jakedcolbert I thought you were creating the issues in your fork?

**Comment by jakedcolbert** [comment]
My mistake
