### ISSUE TITLE
Video options

### ISSUE THREAD

**Issue by chrisvire** [sillsdev/appbuilder-pwa#603]
The feature `video-youtube-related-same-channel` is changed in the Media > Video > Video Settings page:

![Image](https://github.com/sillsdev/appbuilder-pwa/assets/517814/dd3d46c2-f3eb-41b4-83c2-4024e0de8fac)

It looks like we are not accounting for these settings (in `config.mainFeatures`) as well:

```
    "video-allow-fullscreen": true,
    "video-show-titles": true,
    "video-full-screen-width": true,
```

**Comment by davidmoore1** [comment]
The "Use the full width of the screen" option sets feature "video-full-screen-width".  In the Android app, this causes it to override the margin-left and margin-right which are used for the div.video-block style with the values that are set for the body style.  In our case, this would be the styles for the #container.  So find the left and right margins associated with the container, and set those values as the left and right margins for the video div.

For the "video all full screen" option "video-allow-fullscreen", investigate whether it is possible to do this.  For the android app, he only uses this when using a chrome client view.  There is a custom chrome web view that derives from the WebChromeClient.  There is an override of onShowCustomView and onHideCustomView that is called when the user presses the full screen button from within the embedded video.  In that method, it looks like he creates a view of the same size as the original if they are not allowed to use full screen.  I don't know if it is possible to catch the embedded video view button press within PWA, particularly when you have no control of the type of browser being used.
